#################################
#        数据库配置文件         #
#    在这里配置数据库信息       #
#################################

#production: &production
#  adapter: em_mysql2
#  encoding: utf8
#  reconnect: false
#  database: goliathgrape
#  pool: 5
#  username: root
#  password: '913427'
#  host: localhost
#development:
#  <<: *production

production:
  adapter: em_mysql2
  encoding: utf8
  reconnect: false
  database: goliathgrape
  pool: 5
  username: root
  password: '913427'
  host: localhost

development:
  adapter: em_mysql2
  encoding: utf8
  reconnect: false
  database: goliathgrape
  pool: 5
  username: root
  password: '913427'
  host: localhost

